### ISSUE TITLE
Readable/Writable macros not support docs for structures fields

### ISSUE THREAD

**Issue by Klapeyron** [koute/speedy#1]
Hello :),

I have small problem with procedural macros, it looks like they can not parse documentation for the structure fields. Minimal example below:
```rust
#[derive(Readable, Writable)]
struct Foo {
    /// There are some docs for this field
    field: u8
}
```
and error:
`help: message: Unrecognized attribute: NameValue(Ident("doc"), Str("/// There are some docs for this field", Cooked))`

Greetings!

**Comment by koute** [comment]
Fixed in `speedy-derive` 0.3.2 (:
