### ISSUE TITLE
peek_i8 calls read_u8?

### ISSUE THREAD

**Issue by mattfbacon** [koute/speedy#15]
At `src/reader.rs:70`:

```rust
    #[inline(always)]
    fn peek_i8( &mut self ) -> Result< i8, C::Error > {
        self.read_u8().map( |byte| byte as i8 )
    }
```

I feel like `read_u8` should be `peek_u8`. Am I mistaken?

Also, is this maintained?

**Comment by koute** [comment]
> I feel like `read_u8` should be `peek_u8`. Am I mistaken?

Good catch; correct! It was a copy-paste error.

> Also, is this maintained?

It is. It's just what I'd call "stable", so I only make changes when I need to make changes, and otherwise I'm continuously using this crate in production myself.
