### ISSUE TITLE
Readable macro and  minimum_bytes_needed function

### ISSUE THREAD

**Issue by Klapeyron** [koute/speedy#2]
Hello :),

I have short question. It will be possible that procedural macro for Readable will generate and fill minimum_bytes_needed function? I mean below case:

```rust
#[derive(Readable)]
struct Foo {
    field: u8
}
assert_eq!(0, <Foo as Readable<Endianness>>::minimum_bytes_needed());
```
For now it doesn't override such function, so there is used default implementation:
```rust
#[inline]
fn minimum_bytes_needed() -> usize {
    0
}
```

Greetings!

**Comment by koute** [comment]
This is easy enough to add.

Released `speedy-derive` 0.3.3 with `minimum_bytes_needed` generation added. (:

Please note that this isn't guaranteed to return the *exact* number of bytes necessary; it will return the exact number of bytes only when a given structure doesn't have anything dynamically sized inside of it.
