### ISSUE TITLE
trouble implementing trait for reading buffer

### ISSUE THREAD

**Issue by beckend** [koute/speedy#26]
```rust
trait MyDataDecode<TData> {
  fn data_try_from_vec_u8<'a, C: speedy::Context + std::default::Default>(
    x: Vec<u8>,
  ) -> Result<TData>
  where
    TData: Readable<'a, C>,
    <C>::Error: std::fmt::Display,
  {
    match speedy::Readable::read_from_buffer(&x) {
      Ok(x) => Ok(x),
      Err(err) => panic!("{}", err),
    }
  }
}
```
```shell
    |   fn data_try_from_vec_u8<'a, C: speedy::Context + std::default::Default>(
    |                               - this type parameter
...
    |     match speedy::Readable::read_from_buffer(&x) {
    |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected type parameter `C`, found struct `speedy::LittleEndian`
    |
    = note: expected type parameter `C`
                       found struct `speedy::LittleEndian`
```

**Comment by beckend** [comment]
It works fine if implemented in a normal struct.

**Comment by koute** [comment]
Have you tried passing the `C` parameter explicitly? `match speedy::Readable::<'a, C>::read_from_buffer`? That may or may not fix it; I'm not sure from the top of my head.

**Comment by beckend** [comment]
```rust
    |     match speedy::Readable::<'a, C>::read_from_buffer(&x) {
    |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected type parameter `C`, found struct `speedy::LittleEndian`
```

**Comment by koute** [comment]
You can also try `Readable::<'a, C>::read_from_buffer_with_ctx(C::default(), &x)`, which should be functionally equivalent.

**Comment by beckend** [comment]
That one only works if you copy the buffer, the zero copy version will complain about dropped borrow, that is a big deal.

**Comment by beckend** [comment]
Outside trait, I can do zero copy or copy, inside trait, only copy.

**Comment by koute** [comment]
> That one only works if you copy the buffer, the zero copy version will complain about dropped borrow, that is a big deal.

Yeah, that is expected, because you're deserializing from a `Vec<u8>` and you're returning a `Self` which can have a reference to that `Vec<u8>`, so you can't use the zero copy variant.

So what you want is `read_from_buffer_copying_data_with_ctx`. (Or you need to change `Vec<u8>` into `&'a [u8]` if you want to keep on using the potentially zero-copy variant.)

**Comment by beckend** [comment]
Ok this works, thanks you for help!

```rust
trait MyDataDecode<TData> {
  fn data_try_from_vec_u8<'a, C: speedy::Context + std::default::Default>(
    x: &'a [u8],
  ) -> Result<TData>
  where
    TData: Readable<'a, C>,
    <C>::Error: std::fmt::Display,
  {
    match speedy::Readable::read_from_buffer_with_ctx(Default::default(), x) {
      Ok(x) => Ok(x),
      Err(err) => panic!("{}", err),
    }
  }
}
```
