### ISSUE TITLE
Generated code does not work with cycles

### ISSUE THREAD

**Issue by dten** [koute/speedy#3]
Hey I have a type that has a cycle in it, `#[derive(Readable)]` was giving an error about recursion, however manually implementing `Readable` worked. I checked what the generated code looks like and it looked almost identical to what I wrote. Apart from the `where` clause... Removing the where clause makes this code build.

Thoughts :)?

```
error[E0275]: overflow evaluating the requirement `ListNode: speedy::readable::Readable<'_, speedy::endianness::Endianness>`
  --> src/main.rs:12:34
   |
12 |     let r: Result<ListNode, _> = speedy::Readable::read_from_buffer(Endianness::BigEndian, &[]);
   |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = help: consider adding a `#![recursion_limit="128"]` attribute to your crate
   = note: required because of the requirements on the impl of `speedy::readable::Readable<'_, speedy::endianness::Endianness>` for `std::vec::Vec<ListNode>`
   = note: required because of the requirements on the impl of `speedy::readable::Readable<'_, speedy::endianness::Endianness>` for `ListNode`
   = note: required because of the requirements on the impl of `speedy::readable::Readable<'_, speedy::endianness::Endianness>` for `std::vec::Vec<ListNode>`
   = note: required because of the requirements on the impl of `speedy::readable::Readable<'_, speedy::endianness::Endianness>` for `ListNode`
   = note: required because of the requirements on the impl of `speedy::readable::Readable<'_, speedy::endianness::Endianness>` for `std::vec::Vec<ListNode>`
   = note: required because of the requirements on the impl of `speedy::readable::Readable<'_, speedy::endianness::Endianness>` for `ListNode`
```

```
use speedy::{Endianness};

type Set<T> = Vec<T>;
type Map<K, V> = Vec<(K, V)>;

enum ListNode {
  Nil,
  Nodes (Vec<ListNode>),
}

fn main() -> Result<(), Box<std::error::Error>> {
    let r: Result<ListNode, _> = speedy::Readable::read_from_buffer(Endianness::BigEndian, &[]);
    assert!(r.is_ok());

    Ok(())
}

// This bit was generated (i removed the minimum bytes bit though)
impl<'a_, C_: ::speedy::Context> ::speedy::Readable<'a_, C_> for ListNode
where
    i32: ::speedy::Readable<'a_, C_>,
    Vec<ListNode>: ::speedy::Readable<'a_, C_>, // <--- Removing this line makes it compile
{
    #[inline]
    fn read_from<R_: ::speedy::Reader<'a_, C_>>(_reader_: &mut R_) -> ::std::io::Result<Self> {
        let kind_: u8 = _reader_.read_value()?;
        match kind_ {
            0u8 => Ok(ListNode::Tail),
            1u8 => {
                let v0_ = _reader_.read_value()?;
                let v1_ = _reader_.read_value()?;
                Ok(ListNode::Node(v0_, v1_))
            }
            _ => Err(::std::io::Error::new(
                ::std::io::ErrorKind::InvalidData,
                "invalid enum variant",
            )),
        }
    }
}
```

**Comment by dten** [comment]
I'm starting to think you only need the `where` clause for generic type arguments

**Comment by koute** [comment]
> I'm starting to think you only need the where clause for generic type arguments

Yes, the `where` constraints are only necessary when we're dealing with generic type arguments. I'm currently generating an `$type: Readable`/`$type: Writable` bound for every field mostly for two reasons:

1) It's very simple to do.
2) It makes sense. For example, consider the following example:

```rust
struct Dummy<T> {
    phantom: PhantomData<T>
}

impl<'a, C, T> Readable<'a, C> for Dummy<T> { ... }

#[derive(Readable)]
struct Container<T> {
    dummy: Dummy<T>
}
```

This clearly shows that the only bound which makes sense here is `Dummy<T>: Readable`; adding a `T: Readable` bound makes no sense as the generic type `T` has nothing to do with whenever that field is serializable or not, and in cases `T` is meant only as a non-serializable marker type it's really silly to force the user to implement `Readable` for `T`.

I'd argue that the issue of recursive `where` bounds for the same trait should probably be fixed on `rustc` level, however I did push a new version of `serde-derive` (0.3.5) which has a partial workaround for this where in some cases the bounds are not generated. (Unfortunately doing this correctly in every case is not exactly trivial; if someone has a better idea to handle this I'm all ears.) I believe it should fix your problem.

**Comment by dten** [comment]
Thanks I'll try it. I ended up with a fork that did it just for the generic arguments but as you've shown that's not right either
