### ISSUE TITLE
Read vector without length prefix

### ISSUE THREAD

**Issue by nazar-pc** [koute/speedy#4]
Hi, I'd like to be able to read `Vec<u8>` from `[0, 1, 2, 3]`.
Expectation would be to essentially get `vec![0, 1, 2, 3]`, but instead I have to supply `[1, 0, 0, 0, 0, 1, 2, 3]` to de-serialize it with current implementation.

Can you suggest how can I achieve this with speedy library? It seems to fit great otherwise.

Above is a reduced example, but essentially the number of elements in my case can be derived from the length of incoming buffer and thus having first 4 bytes to represent number of elements is redundant. I only have fixed size data types and message-oriented API.

**Comment by koute** [comment]
Yes you can. You can either use `Reader::read_bytes` or `Reader::read_vec` to read a fixed number of bytes if you're manually implementing `Readable`, or you can use `#[speedy(length=$expression)]` attribute if you are `derive`ing your `Readable` where it will use the value of `$expression` instead of reading the length from the bytestream.

If you want to derive the vector length from the size of your buffer then you could do something like this:

```rust
#[derive(Debug)]
struct Message {
    bytes: Vec<u8>
}

struct MyContext {
    length: usize
}

impl speedy::Context for MyContext {
    type Error = speedy::Error;
    fn endianness(&self) -> speedy::Endianness {
        speedy::Endianness::LittleEndian
    }
}

impl<'a> speedy::Readable<'a, MyContext> for Message {
    fn read_from<R>(reader: &mut R) -> Result<Self, speedy::Error>
        where R: speedy::Reader<'a, MyContext>
    {
        let bytes = reader.read_vec(reader.context().length)?;
        Ok(Message { bytes })
    }
}

fn main() {
    use speedy::Readable;
    let raw_msg = &[1, 2, 3];
    let ctx = MyContext {
        length: raw_msg.len()
    };
    let msg = Message::read_from_buffer_with_ctx(ctx, raw_msg).unwrap();
    println!("{:?}", msg);
    // Will print out:
    // Message { bytes: [1, 2, 3] }
}
```

(This is using the current `speedy` from `master`. In general I recommend using it instead of what's currently on crates.io. I've been planning to upload a new version; I just haven't got to updating the documentation with all of the new changes.)

**Comment by nazar-pc** [comment]
I'm already using master branch because I needed HashMap implementation.

The example above makes sense, but it is too lengthy and derive was much nicer.

The use case which is closer to the code I actually have in my app is this:

```rust
#[derive(Readable)]
struct Key(u32);

#[derive(Readable)]
struct Value {
    field: u8,
}


#[derive(Readable)]
struct Elements(HashMap<Key, Value>);
```

And then I can do this whenever I need:
```rust
Elements::read_from_buffer_with_ctx(Endianness::LittleEndian, &bytes)
```

The only problem is that I need to do this hack before using above, which seems much simpler than writing a few implementations of traits (thankfully this code is not performance-critical):
```rust
let bytes = {
    let mut vec = Vec::with_capacity(4 + bytes.len());
    vec.extend_from_slice(&((bytes.len() / block_size) as u32).to_le_bytes());
    vec.extend_from_slice(bytes);
    vec
};
```

Having to implement a few traits for every struct I want to de-serialize makes make want to question usefulness of such approach.

Since it is possible to figure out the size of the both `Key` and `Value` structs, would be nice to have out-of-the-box ability for `Elements` to be parsed as a list of `Key || Value` pairs without length prefix.

Essentially I'd do something like this (pseudo code):
```rust
Elements(
    bytes
        // No prefix needed, cut the thing into pieces
        .chunks_exact(Key::minimum_bytes_needed() + Value::minimum_bytes_needed())
        // (Key, Value) elements are produced here
        .map(|bytes| Readable::read_from_buffer_with_ctx(Endianness::LittleEndian, bytes))
        // Collect as Vec, HashMap, etc.
        .collect()
)
```

**Comment by koute** [comment]
So you'd basically want a `#[speedy(read_until_eof)]` attribute which would just read elements until it encounters an end of stream?

**Comment by nazar-pc** [comment]
Exactly! I'd put that on `Elements` struct.

**Comment by koute** [comment]
This is now implemented as `#[speedy(length = ..)]` on `master`.
