### ISSUE TITLE
Is it possible to implement Readable and Writable for std::result::Result<T, E>

### ISSUE THREAD

**Issue by BobAnkh** [koute/speedy#43]
Since Readable and Writable are implemented for Option, so I wonder if it is possible for the library to implement this for Result?

**Comment by jeromegn** [comment]
Given both `Ok` and `Error` values implement `Readable` and `Writable`? I assume it would be possible. Maybe like `Option<T>`, prefix with `0` is `Ok` and prefix with `1` if `Error`.

**Comment by BobAnkh** [comment]
I would like to implement this feature so I wonder if this will be accepted. @koute

**Comment by koute** [comment]
> I would like to implement this feature so I wonder if this will be accepted. @koute

Yes, I'll merge such a PR.
