### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by jnises** [koute/speedy#55]
Hi.
A new release of speedy with the glam 0.24 dependency bump that is in master would allow us to publish some of our crates that depend on it.

Do you have any timeline for when the next release will come?

**Comment by jeromegn** [comment]
I'm also interested in a new release since my PR (#52) was merged. I've had to publish my own crate and alias it in the meantime.

**Comment by fornwall** [comment]
Speedy `0.8.7` was released today (thanks @koute), so this issue can be closed.
