### ISSUE TITLE
Referencing a nested struct field in the length macro causes weird behaviour in referencing projects

### ISSUE THREAD

**Issue by MidasLamb** [koute/speedy#7]
I have a cargo workspace with two projects, a lib and an exe.

The lib defines the structs, and there is following structure present there:
```
pub struct Data {
    pub nested: Nested,
    #[speedy(length = nested.message_length - 44 - 4 )]
    pub bytes: Vec<u8>
}

pub struct Nested {
    pub message_length: u32,
    ...
}
```

The tests on the lib work fine, but if I run cargo check on the exe, which references the lib, i get weird errors (redacted):
![image](https://user-images.githubusercontent.com/14802865/87957296-5fe32d00-cab0-11ea-9d8f-c1d57e9477dc.png)

Pulling the `message_length` upwards resolves these errors, but it's very strange the lib itself can be build, but when used as a dependency it can't?

**Comment by koute** [comment]
As far as I can see that's a bug in `syn` 1.0.33 where it suddenly can't parse the `nested.message_length` expression. As a workaround you should be able to add `syn = "=1.0.32"` to your `Cargo.toml` (please let me know if that works for you).

**Comment by koute** [comment]
Reported this here: https://github.com/dtolnay/syn/issues/870

**Comment by MidasLamb** [comment]
I've tried to add it to Cargo.toml but it didn't seem to have any impact (i.e. it didn't seem to pull the correct version) (I don't have much experience with the workspaces), but I saw that it now pulled 1.0.35 of syn and now it works!
